version: '3.7'

services:
  dnsmasq:
    image: andyshinn/dnsmasq
    volumes:
      - ./dnsmasq:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    restart: always

  web_google:
    build:
      context: ./web
    volumes:
      - ./web/google:/usr/share/nginx/html
    ports:
      - "8080:80"

  web_ionos:
    build:
      context: ./web
    volumes:
      - ./web/ionos:/usr/share/nginx/html
    ports:
      - "8090:80"

  web_nazwa:
    build:
      context: ./web
    volumes:
      - ./web/nazwa:/usr/share/nginx/html
    ports:
      - "8100:80"
